### ISSUE TITLE
Add .babelrc to .npmignore for React Native compatibility

### ISSUE THREAD

**Issue by shaikatz** [Gabrn/react-native-persistent-job#1]
Please remove .babelrc from the npm package, as it breaks things on React Native. See here:
https://github.com/facebook/react-native/issues/4062

Thank you!

**Comment by GabiNir** [comment]
https://github.com/GabiNir/react-native-persistent-job/commit/8532abce0cd94980908e1f6cc5e72be75532c177

**Comment by Gabrn** [comment]
https://github.com/GabiNir/react-native-persistent-job/commit/039df0b7d69e97bda571084ac85d7df5fabaf710
