### ISSUE TITLE
Concurrent Job Creation Unsafe?

### ISSUE THREAD

**Issue by billmalarky** [Gabrn/react-native-persistent-job#2]
Looking at the job persistence logic, appears the jobs are backed by AsyncStorage.

If you are adding a lot of jobs concurrently it looks like jobs could be dropped.

https://github.com/Gabrn/react-native-persistent-job/blob/master/lib/jobPersistence.ts#L30-L51

If I'm reading this correctly, it looks like you are storing an incrementing id "serialNumber" which is used to uniquely identify the jobs as well as query for the jobs later.

The problem occurs if you are concurrently creating jobs, AsyncStorage could return the same serial number value to each job, then they both would increment it, then save the job with the same id in persistNewJob(). So one of the jobs will get dropped.

Am I on to something here?

**Comment by Gabrn** [comment]
@billmalarky Thanks for the input!
I think you are indeed on to something.
I use 2 seperate requests to async storage one to update `currentSerialNumber` and another to update the job for that serial number and I don't save `currentSerialNumber` in a constant before. So the eventloop might give another `persistNewJob` the turn and thus persist both jobs under the same key.

**Comment by Gabrn** [comment]
7af78efafead95464d023bf7101f5eed26ba5b7f

**Comment by billmalarky** [comment]
Yeah so long as you add some sort of in memory tracking it will be fine so
long as everything is running in one js thread.

Glad to help!
